// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQqviDjtB49SiM9mTdTFSu9r7SLpgiMRc',
    appId: '1:1032099908318:web:eb4f70ff8d758433dd904f',
    messagingSenderId: '1032099908318',
    projectId: 'vigo-smarterp',
    authDomain: 'vigo-smarterp.firebaseapp.com',
    storageBucket: 'vigo-smarterp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqskgADIkEUSfgKgnEhNnHmJEubP7ndGU',
    appId: '1:1032099908318:android:6bd66d87a3343e52dd904f',
    messagingSenderId: '1032099908318',
    projectId: 'vigo-smarterp',
    storageBucket: 'vigo-smarterp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnJKX9AcjfwtDL_Mf4OcssUBpJ8pdOjM',
    appId: '1:1032099908318:ios:14f47046b5fc3732dd904f',
    messagingSenderId: '1032099908318',
    projectId: 'vigo-smarterp',
    storageBucket: 'vigo-smarterp.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwnJKX9AcjfwtDL_Mf4OcssUBpJ8pdOjM',
    appId: '1:1032099908318:ios:14f47046b5fc3732dd904f',
    messagingSenderId: '1032099908318',
    projectId: 'vigo-smarterp',
    storageBucket: 'vigo-smarterp.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQqviDjtB49SiM9mTdTFSu9r7SLpgiMRc',
    appId: '1:1032099908318:web:7392a2634ba01fc2dd904f',
    messagingSenderId: '1032099908318',
    projectId: 'vigo-smarterp',
    authDomain: 'vigo-smarterp.firebaseapp.com',
    storageBucket: 'vigo-smarterp.appspot.com',
  );
}
